version: '3.3'

services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 3309:8080
    depends_on:
      - mysql